# frozen_string_literal: true

module DeprecationCollector
  List =
    # Ember deprecations (generated by `/list_ember_deprecations.rb`)
    %w[deprecate-implicit-route-model] +
      # discourse deprecations
      %w[
        discourse.modal-controllers
        discourse.global.user
        discourse.global.site
        discourse.global.site-settings
        discourse.bootbox
      ]
end
